# Generated by Django 5.2.3 on 2025-07-24 09:29

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_department'),
        ('sisan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='所属している学科を選択できます', on_delete=django.db.models.deletion.PROTECT, to='sisan.department', verbose_name='所属学科'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='この項目は必須です。メールアドレスは公開されません。', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='この項目は必須です。全角文字、半角英数字、@/./+/-/_ で50文字以下にしてください。', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザー名'),
        ),
    ]
