# Generated by Django 5.2.3 on 2025-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_department_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='この項目は必須です。メールアドレスは公開されません。', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
