# Generated by Django 5.2.3 on 2025-07-24 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学科名')),
            ],
        ),
        migrations.CreateModel(
            name='Sisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sisan_id', models.CharField(max_length=100, verbose_name='資産管理番号')),
                ('name', models.CharField(max_length=100, verbose_name='型式番号')),
                ('buy_date', models.DateField(verbose_name='取得年月日')),
                ('remove_date', models.DateField(blank=True, null=True, verbose_name='除却年月日')),
                ('price', models.IntegerField(verbose_name='取得価格')),
                ('place', models.CharField(max_length=100, verbose_name='保管場所')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
        ),
    ]
